# Generated by Django 4.0.5 on 2023-02-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=254)),
                ('messsage', models.TextField(max_length=300)),
            ],
        ),
    ]
