# Generated by Django 4.0.5 on 2023-02-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
