# Generated by Django 4.0.5 on 2022-10-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_img_alter_job_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
    ]
