# Generated by Django 4.0.5 on 2022-11-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('websit', models.URLField()),
                ('cv', models.FileField(upload_to='aplly/')),
                ('coverletter', models.TextField()),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
