# Generated by Django 4.0.5 on 2022-11-20 00:25

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_title_job_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, upload_to=job.models.photo),
        ),
    ]
