# Generated by Django 4.0.5 on 2022-11-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_job_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='title',
        ),
    ]
