# Generated by Django 4.0.5 on 2023-02-02 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0016_like_or_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_or_unlike',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
