# Generated by Django 4.0.5 on 2023-02-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_like_or_unlike_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like_or_unlike',
        ),
    ]
