# Generated by Django 4.0.5 on 2023-02-03 19:26

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_delete_like_or_unlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_cat',
            field=models.ImageField(default=1, upload_to='cat_photo/%y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.photo),
        ),
    ]
