# Generated by Django 4.0.5 on 2023-02-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_category_photo_cat_alter_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Country',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
